### PR TITLE
CSS: table, figure, caption alignment

### PR DESCRIPTION
**Pull request by dhimmel**
Closes https://github.com/greenelab/manubot-rootstock/issues/130

I'm far from a proficient CSS developer, so please double check whether what I'm doing makes sense.

Have not tested yet.

### CODE REVIEW

**Comment by dhimmel** [comment]
We've got to update the img style to only apply to img when part of a figure.

> screenshot from 2018-08-03 16-39-56

**Comment by dhimmel** [comment]
Using CSS from https://github.com/greenelab/manubot-rootstock/pull/131/commits/247ddf9c16e21000db7d47d21a7abbf2beb45019, here is the Meta Review PDF: [css-style-output.pdf](https://github.com/greenelab/manubot-rootstock/files/2258784/css-style-output.pdf)

**Comment by agitter** [comment]
> Using CSS from 247ddf9, here is the Meta Review PDF: css-style-output.pdf.

That version looks good.

**Comment by dhimmel** [comment]
@slochower mind taking a look?

**Comment by slochower** [comment]
LGTM!

**Pull request merged**
