### PR TITLE
Usage examples: add TFSEE

### PR DESCRIPTION
**Pull request by dhimmel**
As suggested in https://github.com/greenelab/meta-review/issues/45#issuecomment-401613937

@vsmalladi can you review?

### CODE REVIEW

**Comment by dhimmel** [comment]
We're adding an additional example to the Usage section, so I thought it'd be a good time to possible add additional manuscripts from https://github.com/greenelab/manubot-rootstock/issues/67.

@MatthewTurk / @yt-project mind if we add your "Introducing yt 3.0: Analysis and Visualization of Volumetric Data" manuscript to the usage examples? We'd link to the [GitHub](https://github.com/yt-project/yt-3.0-paper) and [HTML manuscript](https://yt-project.github.io/yt-3.0-paper/)?

@openclimatedata / @rgieseke, what about "Global Emissions Timeseries" ([GitHub](https://github.com/openclimatedata/global-emissions) and [HTML manuscript](https://openclimatedata.github.io/global-emissions/)? BTW I like the "work-in-progress" banner. That's cool.

**Comment by rgieseke** [comment]
Happy to see it included, though it's very, very early stages ...

>  BTW I like the "work-in-progress" banner. That's cool.

Thanks, I'll file an issue to maybe add similar functionality via a config file ...

**Comment by dhimmel** [comment]
Cool, I added the global emissions and yt 3.0 links in https://github.com/greenelab/manubot-rootstock/pull/127/commits/c47264ab8a6f80a3d1d9d4d9443565ae7976396e. Will get in touch with @MatthewTurk / @yt-project to make sure this is OKAY.

**Comment by MatthewTurk** [comment]
It is okay with me!  But we have not been moving as quickly as I had hoped.

**Comment by dhimmel** [comment]
> It is okay with me! But we have not been moving as quickly as I had hoped.

Not a problem! These examples are more for people to see different Manubot instances to help evaluate whether it fits their needs. I don't think most readers will care if the examples are completed or not.

Let us know if there are any Manubot painpoints we can address to help yt move forward!

**Comment by MatthewTurk** [comment]
...can you make it write the paper for us?  ;-)

**Pull request merged**
