### PR TITLE
Update 02.equations.md to fix typo

### PR DESCRIPTION
**Pull request by slochower**
Fix typo: delimeters → delimiters

I followed the suggested [steps](https://github.com/cognoma/cognoma/blob/master/CONTRIBUTING.md#contribution-workflow) however, it seems both typo commits are in this single PR. Specifically, since I already have a fork I did:

1. `git checkout -b typo`
2. `git status` to make sure I was up to date.
3. (Fix the typo)
4. `git add content/02.equations.md`
5. `git commit -m "Update 02.equations.md" -m "Fix typo: delimeters → delimiters"`
6. `git push mymanubot` (Push to my local fork)
7. (Request the PR)

Is that the correct sequence?

### CODE REVIEW

**Comment by dhimmel** [comment]
Your issue is likely that you ran `git checkout -b typo` from a branch that had diverged from `greenelab:master`.

Try:

```
git fetch upstream
git rebase upstream/master
# If everything worked do
git push --force
```

**Comment by slochower** [comment]
The `rebase` gets me stuck in some sort of loop that I don't completely understand.

I made some changes then tried to follow the instructions at https://github.com/greenelab/manubot-rootstock/issues/6#issuecomment-315129638 followed by `git push origin master` to push into my fork. 
```
$ git push origin master
Everything up-to-date
```
But if I check status, I still see
```
$ git status
rebase in progress; onto 83659ae
You are currently rebasing branch 'master' on '83659ae'.
  (all conflicts fixed: run "git rebase --continue")

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	build/authors.py
	content/authors.tsv

nothing added to commit but untracked files present (use "git add" to track)
```
If I do a `git add .` then it tries to add `content/authors.tsv` back into my fork, instead of removing and replacing it with the `metadata.yaml` approach.

I don't mean to offload troubleshooting to you, but I think it's still unclear how to work with `greenelab/manubot-rootstock` as a remote (for me). Are there updated instructions that work for your SciHub manuscript that aren't in https://github.com/greenelab/manubot-rootstock/issues/6?

**Comment by slochower** [comment]
(I should add that doing `git rebase --continue`, as suggested, does not solve the problem. It still tries to add a local `authors.tsv` to my commit.)

**Comment by evancofer** [comment]
Not sure if this helps, but I figured I might chime in. I had a similar issue when I tried rebasing my branch. I ended up just merging master into my fork instead, and for  reasons largely unknown to me it went more smoothly.

**Comment by slochower** [comment]
@evancofer Thanks for the input. Do you happen to have the history of the exact commands you used so I can try and see if this works for me?

**Pull request closed without merging**
