### PR TITLE
Update SETUP.md based on OpenCon do-a-thon

### PR DESCRIPTION
**Pull request by dhimmel**
Work in progress.

Thanks @zambujo @RaoOfPhysics @broadwym @schliebs @Hillea and others who've stopped by our OpenCon Do-A-Thon table. See https://github.com/sparcopen/doathon/issues/21 for more info.

Attendees have begun setting up manuscripts. We've noticed some pain points and difficulties. This PR aims to improve the `SETUP.md` documentation in response to these issues.

Feel free to review this PR or make additional doc suggestions.

### CODE REVIEW

**Comment by dhimmel** [comment]
> That's what I use on Windows.

Windows doesn't come with Ruby or Python right? So we're requiring users to install at least 2 languages... eek!

**Comment by agitter** [comment]
That's right.  During my setups, I abandoned Windows for the Ruby/Travis steps though.  I don't recall if it was because of this [Travis caveat](https://docs.travis-ci.com/user/encrypting-files/#Caveat) or if I just thought it would be easier.

**Comment by dhimmel** [comment]
> 👍  on Git Bash. That's what I use on Windows.

@agitter we may need to rethink our windows support based on the `deploy.key` encryption nightmare in https://github.com/greenelab/manubot-rootstock/issues/91

**Comment by agitter** [comment]
Do we officially support Windows now?  Our conda environment doesn't.  I assumed we recommend Linux for setup as well, so I'm okay making that official.

I think that reaching the broadest user base possible would require highly-automated setup via a GitHub app instead of Windows command line support.

**Comment by dhimmel** [comment]
> Do we officially support Windows now?

No. Although I think I should edit this PR to say that Windows may work with the Linux Subsystem, and otherwise will not work.

> Our conda environment doesn't

I thought it was possible that the conda environment now works on windows? From https://github.com/greenelab/manubot-rootstock/pull/78, it seems like the environment may work if visual C++ is installed?

> I think that reaching the broadest user base possible would require highly-automated setup via a GitHub app instead of Windows command line support.

Yes, I would venture to say that at the moment, most of the users with sufficient technical experience to setup a manuscript, probably do not exclusively use windows?

**Comment by agitter** [comment]
> Windows may work with the Linux Subsystem, and otherwise will not work.

Agreed.  We could mention Docker as an untested option or avoid it until we've tested it.  [My Docker test](https://github.com/greenelab/manubot-rootstock/issues/6#issuecomment-319089862) was in Linux but provides a relevant container.

> I thought it was possible that the conda environment now works on windows?

Yes, it's likely to work if there is a C++ compiler available.  I was referring to our build readme, where we still say `Currently, the environment requires Linux.`  I agree with that message until we've successfully built a manuscript on Windows.

> most of the users with sufficient technical experience to setup a manuscript, probably do not exclusively use windows

👍

**Comment by dhimmel** [comment]
> I was referring to our build readme, where we still say Currently, the environment requires Linux.

Updated this in https://github.com/greenelab/manubot-rootstock/pull/89/commits/a3b9206f484ca61f566fcfc4cadc648e4ae0b64e.

@agitter can you re-review with the latest changes?

**Pull request merged**
