### PR TITLE
Update 03.figures.md

### PR DESCRIPTION
**Pull request by slochower**
Fix typo: LigGen → LigGen

### CODE REVIEW

**Comment by slochower** [comment]
Absurdly, I made the same mistake in commit message for this (34dde9e). The actual commit is correct though. In `03.figures.md`, I wrote "LigGen" instead of "LibGen" which this commit fixes.

**Comment by dhimmel** [comment]
> Absurdly, I made the same mistake in commit message for this

You can fix it with

```
git commit --amend
git push --force
```

**Comment by dhimmel** [comment]
> You can fix it with

Ah you did on GitHub... that makes it harder to amend a commit.

I updated the commit message during the squash merge.

**Comment by slochower** [comment]
Nice, thanks. Yes, I did that small change on GH because my own fork had several other changes and I'm not sure how to make a PR for just one change among many.

**Comment by dhimmel** [comment]
> Yes, I did that small change on GH because my own fork had several other changes and I'm not sure how to make a PR for just one change among many.

Read over the workflow here https://github.com/cognoma/cognoma/blob/master/CONTRIBUTING.md#contribution-workflow

Each PR should be coming from a different branch of your fork (preferably not `master` to avoid confusion). Then you can just checkout whichever branch you need for a given PR.

**Pull request merged**
