### PR TITLE
WIP: Pandoc export to JATS XML

### PR DESCRIPTION
**Pull request by dhimmel**
This is a work in progress to create a [JATS XML](https://en.wikipedia.org/wiki/Journal_Article_Tag_Suite) export of manuscripts.

It relies on [`pandoc-jats`](https://github.com/mfenner/pandoc-jats) by @mfenner.

JATS XML may be useful for submission to journals, a standardized format for text mining, and import to other manuscript editors such as [Texture](https://github.com/substance/texture). In addition, we could potentially use a JATS viewer to render the manuscript in a web browser. This could potentially replace or supplement our current HTML output.

### CODE REVIEW

**Comment by dhimmel** [comment]
As of https://github.com/greenelab/manubot-rootstock/pull/51/commits/c07c779d7b4e34cf9da0ba60d10bdb87eaa28b05, `manuscript.xml` looks like:

<details>
  <summary>Expand to see manuscript.xml</summary>

```xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE article PUBLIC "-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v1.0 20120330//EN"
                  "JATS-journalpublishing1.dtd">
<article xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xlink="http://www.w3.org/1999/xlink" dtd-version="1.0" article-type="other">
<front>
<journal-meta>
<journal-title-group>
</journal-title-group>
<publisher>
<publisher-name></publisher-name>
</publisher>
</journal-meta>
<article-meta>
<title-group>
<article-title>Manubot Rootstock: Manuscript Title</article-title>
</title-group>
</article-meta>
</front>
<body>
<sec id="sec-1">
<title/>
<p><preformat>html</preformat><preformat>html</preformat>This manuscript was automatically generatedon August 10, 2017.<preformat>html</preformat><preformat>html</preformat></p>
</sec>
<sec id="sec-1.1">
<title>Authors</title>
<list list-type="bullet">
<list-item><p><bold>Daniel S. Himmelstein</bold><preformat>html</preformat><graphic mimetype="image" xlink:href="images/orcid.svg" xlink:type="simple">ORCID icon</graphic><ext-link ext-link-type="uri" xlink:href="https://orcid.org/0000-0002-3012-7446" xlink:type="simple">0000-0002-3012-7446</ext-link>· <graphic mimetype="image" xlink:href="images/github.svg" xlink:type="simple">GitHub icon</graphic><ext-link ext-link-type="uri" xlink:href="https://github.com/dhimmel" xlink:type="simple">dhimmel</ext-link>· <graphic mimetype="image" xlink:href="images/twitter.svg" xlink:type="simple">Twitter icon</graphic><ext-link ext-link-type="uri" xlink:href="https://twitter.com/dhimmel" xlink:type="simple">dhimmel</ext-link><preformat>html</preformat><preformat>html</preformat>Department of Systems Pharmacology and Translational Therapeutics, University of Pennsylvania· Funded by GBMF4552<preformat>html</preformat></p></list-item>
<list-item><p><bold>Anthony Gitter</bold><preformat>html</preformat><graphic mimetype="image" xlink:href="images/orcid.svg" xlink:type="simple">ORCID icon</graphic><ext-link ext-link-type="uri" xlink:href="https://orcid.org/0000-0002-5324-9833" xlink:type="simple">0000-0002-5324-9833</ext-link>· <graphic mimetype="image" xlink:href="images/github.svg" xlink:type="simple">GitHub icon</graphic><ext-link ext-link-type="uri" xlink:href="https://github.com/agitter" xlink:type="simple">agitter</ext-link><preformat>html</preformat><preformat>html</preformat>Department of Biostatistics and Medical Informatics, University of Wisconsin-Madison and Morgridge Institute for Research· Funded by NIH U54AI117924<preformat>html</preformat></p></list-item>
<list-item><p><bold>Venkat S. Malladi</bold><preformat>html</preformat><graphic mimetype="image" xlink:href="images/orcid.svg" xlink:type="simple">ORCID icon</graphic><ext-link ext-link-type="uri" xlink:href="https://orcid.org/0000-0002-0144-0564" xlink:type="simple">0000-0002-0144-0564</ext-link>· <graphic mimetype="image" xlink:href="images/github.svg" xlink:type="simple">GitHub icon</graphic><ext-link ext-link-type="uri" xlink:href="https://github.com/vsmalladi" xlink:type="simple">vsmalladi</ext-link><preformat>html</preformat><preformat>html</preformat>The Laboratory of Signaling and Gene Expression, Cecil H. and Ida Green Center for Reproductive Biology Sciences, University of Texas Southwestern Medical Center<preformat>html</preformat></p></list-item>
<list-item><p><bold>Evan M. Cofer</bold><preformat>html</preformat>· <graphic mimetype="image" xlink:href="images/github.svg" xlink:type="simple">GitHub icon</graphic><ext-link ext-link-type="uri" xlink:href="https://github.com/evancofer" xlink:type="simple">evancofer</ext-link><preformat>html</preformat><preformat>html</preformat><preformat>html</preformat></p></list-item>
</list>
</sec>
<sec id="sec-1.1.1">
<title>Equations</title>
<p>Numbered equations can be included by using <preformat>$$</preformat> delimiters with embedded LaTeX math.Equations can be labeled with tags like this <preformat>{#eq:label}</preformat> and referenced in text using <preformat>@eq:label</preformat>.</p>
<p><disp-formula> y = mx + b \qquad (1)</disp-formula> </p>
<p>Equation <ext-link ext-link-type="uri" xlink:href="#eq:line" xlink:type="simple">1</ext-link> is the equation for a line in slope-intercept form.</p>
</sec>
<sec id="sec-1.1.2">
<title>Figures</title>
<p>Numbered figures can be included by using the format <preformat>![Caption text](URL){#fig:label}</preformat>.The figures can be referenced in the text by using <preformat>@fig:label</preformat>.</p>
<p>Figure <ext-link ext-link-type="uri" xlink:href="#fig:googletrends" xlink:type="simple">1</ext-link> shows the interest for "Sci-Hub" and "LibGen" over time.</p>
<fig id="g001"><caption>https://cdn.rawgit.com/greenelab/scihub/7891082161dbcfcd5eeb1d7b76ee99ab44b95064/explore/trends/google-trends.svg</caption><graphic mimetype="image" xlink:href="fig:" xlink:title="Figure 1: Google Trends Search interest for Sci-Hub and LibGen." xlink:type="simple"/></fig>
</sec>
<sec id="sec-1.1.3">
<title>Tables</title>
<p>Numbered tables can be included by using Markdown syntax to create the table and then adding a tag after the caption like this <preformat>{#tbl:label}</preformat>.The tables can be referenced in the text by using <preformat>@tbl:label</preformat>.</p>
<p>Table <ext-link ext-link-type="uri" xlink:href="#tbl:interest" xlink:type="simple">1</ext-link> shows the relative search interest of the terms "Sci-Hub" and "LibGen" the week of June 25, 2017.</p>
<table-wrap>
<caption>><p>Table 1: Google Trends Search interest for Sci-Hub and LibGen. </caption>>
<table>
<tr>
<th align="left">week</th>
<th align="left">search_term</th>
<th align="left">interest</th>
</tr>
<tr>
<td align="left">2017-06-25</td>
<td align="left">LibGen</td>
<td align="left">47</td>
</tr>
<tr>
<td align="left">2017-06-25</td>
<td align="left">Sci-Hub</td>
<td align="left">56</td>
</tr>
</table>
</table-wrap>
<p>1. Ching T <italic>et al.</italic> 2017 Opportunities And Obstacles For Deep Learning In Biology And Medicine. See <ext-link ext-link-type="uri" xlink:href="https://doi.org/10.1101/142760" xlink:type="simple">https://doi.org/10.1101/142760</ext-link>.</p>
<p>2. Himmelstein D. 2017 greenelab/manubot-rootstock GitHub repository. <italic>GitHub</italic>. See <ext-link ext-link-type="uri" xlink:href="https://github.com/greenelab/manubot-rootstock" xlink:type="simple">https://github.com/greenelab/manubot-rootstock</ext-link>.</p></sec>
</body>
</article>
```
</details>

**Comment by agitter** [comment]
Is the abstract missing?

**Comment by dhimmel** [comment]
> Is the abstract missing?

Yeah! Odd! @mfenner

**Comment by dhimmel** [comment]
# Official Pandoc support for JATS output

From [this post](https://groups.google.com/d/msg/pandoc-discuss/09XJwmrTXjI/hNKYso_5AgAJ) from March 30, 2017 by pandoc author @jgm:

> I've just added a JATS XML writer to the dev version of pandoc, drawing on earlier work of @mfenner and others. It includes bibliography handling via pandoc-citeproc and proper math handling. 

Looking through the pandoc source code history, JATS export support was added in https://github.com/jgm/pandoc/commit/831e1c5edd4703b6ab0953a79980e37ea1bee5dc.

@jgm any estimate of the release timeframe for JATS writer support?

**Comment by jgm** [comment]
+++ Daniel Himmelstein [Aug 12 17 01:45 ]:
>   [5]@jgm any estimate of the release timeframe for JATS writer support?

This release cycle is a major one, with many, many changes.
I'd anticipate some time this Fall, but I can't say when.

**Comment by dhimmel** [comment]
[Pandoc 2.0](https://github.com/jgm/pandoc/releases/tag/2.0) released today with JATS support. I will submit a PR to [`conda-forge/pandoc-feedstock`](https://github.com/conda-forge/pandoc-feedstock) to see if we can update the conda-forge version.

**Comment by dhimmel** [comment]
Moved to https://github.com/greenelab/manubot-rootstock/pull/82 which uses pandoc's builtin JATS writer

**Pull request closed without merging**
